version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysqlpunch
      MYSQL_USER: puncher
      MYSQL_PASSWORD: punchpasswd
      MYSQL_ROOT_PASSWORD: punchpasswd
    ports:
      # This port is set so you can use tools like mysql workbench to visualize changes to the tables in this db as you iterate.
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: